#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


exec newrelic-admin run-program gunicorn config.asgi:application \
    --bind 0.0.0.0:5000 \
    --chdir=/app \
    -k uvicorn.workers.UvicornWorker
